### ISSUE TITLE
using py launcher instead of python for windows

### ISSUE THREAD

**Issue by pingu6** [sublimelsp/lsp_utils#121]
https://github.com/sublimelsp/lsp_utils/blob/main/st3/lsp_utils/pip_client_handler.py#L54
Hi, i think it would be better to use py launcher instead of python, i don't know about other people but it's recommended to add only py launcher to windows path and not python because it cause problem when having multiple version of python (https://gist.github.com/sgtlaggy/72aec5354607efbf75e4780aab7c9c54#common-issues)

**Comment by jfcherng** [comment]
He reported on Discord. He's on Windows and has no `python` in `PATH`. Instead, he has `py` in `PATH`. Fwiw, ST's built-in build system use `py` on Windows: https://github.com/sublimehq/Packages/blob/23c715e21cf1ab17675e8ef6cf3451c349a16acd/Python/Python.sublime-build#L9
