### ISSUE TITLE
Python binary "py" not found!

### ISSUE THREAD

**Issue by munkybutt** [sublimelsp/lsp_utils#129]
Morning,

lsp_utils updated to 3.2.1 this morning and now I get this error which makes LSP fall over :(

``` python
# Unable to start subprocess for LSP-ruff
Traceback (most recent call last):
  File "C:\Users\Shea.Richardson\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 257, in start_async
    if plugin_class.needs_update_or_installation():
  File "C:\Users\Shea.Richardson\AppData\Roaming\Sublime Text\Lib\python38\lsp_utils\_client_handler\abstract_plugin.py", line 101, in needs_update_or_installation
    server = cls.get_server()
  File "C:\Users\Shea.Richardson\AppData\Roaming\Sublime Text\Lib\python38\lsp_utils\pip_client_handler.py", line 66, in get_server
    raise Exception('Python binary "{}" not found!'.format(python_binary))
Exception: Python binary "py" not found!
```
looking at the history "py" used to be "python" - could this option be exposed to settings so we can control it?

**Comment by rchl** [comment]
If it's a widespread issue then we should either revert or make it auto-detect the one to use but I wonder why `py` is not available in your case. I think it should be by default when using the official python installer. What's special in your setup?

**Comment by jfcherng** [comment]
> If it's a widespread issue then we should either revert or make it auto-detect the one to use but I wonder why `py` is not available in your case. I think it should be by default when using the official python installer. What's special in your setup?

Probably we can have `python` as a fallback. Something like `which('py') or which('python')`.

**Comment by munkybutt** [comment]
> If it's a widespread issue then we should either revert or make it auto-detect the one to use but I wonder why `py` is not available in your case. I think it should be by default when using the official python installer. What's special in your setup?

We deploy python using `pyenv-win` which as far as I can tell, doesn't define the `py` keyword.

**Comment by rchl** [comment]
Created https://github.com/sublimelsp/lsp_utils/pull/130

**Comment by rchl** [comment]
Version with the fix should be available in max 24h
