### ISSUE TITLE
Bring common pip-based code to this library

### ISSUE THREAD

**Issue by rwols** [sublimelsp/lsp_utils#16]
Compare https://github.com/sublimelsp/LSP-pyls/blob/master/plugin.py and https://github.com/sublimelsp/LSP-anakin/blob/master/plugin.py

**Comment by rwols** [comment]
And also compare https://github.com/sublimelsp/LSP-cmake/blob/master/plugin.py

**Comment by rchl** [comment]
Implementing this in https://github.com/sublimelsp/lsp_utils/pull/41

Looking at LSP-anakin and LSP-cmake, I see that those check installed version using `--version` and I wonder if those can do it the same as LSP-pyls. Namely, check the existing version using `pip freeze`.

**Comment by rwols** [comment]
They should use pip freeze as well.

**Comment by rchl** [comment]
Introduced in https://github.com/sublimelsp/lsp_utils/releases/tag/1.10.0
