### ISSUE TITLE
Script to parse VSCode's package.json

### ISSUE THREAD

**Issue by rwols** [sublimelsp/lsp_utils#18]
It's boring to write out settings.

Because most language servers have a package.json file, read that file, and then generate two files:

1) The schema file for the server settings
2) ~~Placeholder JSON for the actual server settings~~

**Comment by rwols** [comment]
> Placeholder JSON for the actual server settings

This is now done.

**Comment by rchl** [comment]
> The schema file for the server settings

For that, we wouldn't need to do anything special once we have https://github.com/sublimelsp/LSP-json/pull/43 . We would need to just copy-paste the relevant part from the original package.json.

**Comment by rchl** [comment]
This is now available in LSP package.
