### ISSUE TITLE
`sublime_lib` is used but not in `dependencies.json` here

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/lsp_utils#35]
`sublime_lib` is used in https://github.com/sublimelsp/lsp_utils/blob/553a579741063a46e1da91b1d2f5b062282ede1e/st3/lsp_utils/server_npm_resource.py#L8

---

`LSP-*` plugins which are based on NPM, for example `LSP-pyright`, work because they add `sublime_lib` in their [`dependencies.json`](https://github.com/sublimelsp/LSP-pyright/blob/394ea37f630452ac853a174805a8de96beb4f479/dependencies.json) but `LSP-pyright` doesn't use `sublime_lib` directly.

---

I am not sure whether `dependencies.json` works in a repo which is a dependency.

**Comment by rchl** [comment]
Dependency can't depend on another dependency. It needs to be done like it is done now - the package needs to include all needed dependencies. It's also stated at https://github.com/sublimelsp/lsp_utils#how-to-use

**Comment by jfcherng** [comment]
Ah, I am such a dump. I guess I definitely read the README when I create LSP-* a long time ago :laughing:
