### ISSUE TITLE
Need callback for on_pre_server_command

### ISSUE THREAD

**Issue by rwols** [sublimelsp/lsp_utils#43]
The on_pre_server_command callback from AbstractPlugin is one of the most important callbacks to realize the full potential of a server with some tight client glue code. I'm missing this callback in the GenericClientHandler.

**Comment by rchl** [comment]
It's not explicitly documented but it will work if you try to use it since in ST4 the `GenericClientHandler` inherits from `AbstractPlugin`. Of course, it won't work in ST3 and I don't think I have the capacity to add support for it there...

**Comment by rwols** [comment]
Seems to work fine indeed :)
