### ISSUE TITLE
enabled setting for LSP- client not respected

### ISSUE THREAD

**Issue by braver** [sublimelsp/lsp_utils#46]
**Describe the bug**
 I've "globally disabled" LSP-intelephense, but it's still initializing and running for new windows.

This is in my settings:
```json
"clients":
{
    "LSP-intelephense":
    {
        "enabled": false
    }
},
```

**To Reproduce**
1. Use the command "LSP: disable language server globally" 
2. Restart ST (maybe? just to be sure)
3. Open a new directory that the language server would work on
4. Observe that the language server still initialises and runs

**Expected behavior**
My idea here was to disable LSP-intelephense globally, and then enable it for a selected project. Ie. most of my projects are legacy stuff where it doesn't work / provide benefits. But in the one modern project I do want to use. 

**Screenshots**

**Environment (please complete the following information):**
- OS: macOS 11.0.1 (Big Sur)
- Sublime Text version: 4094
- LSP version: 1.2.0
- Language servers used: LSP-intelephense 1.0.12

**Comment by rchl** [comment]
Will be resolved in https://github.com/sublimelsp/lsp_utils/releases/tag/1.10.0
