### ISSUE TITLE
Support mac arm64

### ISSUE THREAD

**Issue by rchl** [sublimelsp/lsp_utils#60]
It seems like Mac ARM is supported from node 16 which is not ideal since some servers don't like to run on node > 14 currently.

**Comment by jfcherng** [comment]
do you mean the 'auto node installtion' from this dep?

**Comment by rchl** [comment]
Yes

**Comment by jfcherng** [comment]
i guess it is time to do https://github.com/sublimelsp/lsp_utils/pull/59 for it then.

**Comment by rchl** [comment]
Yes but see my point above.

**Comment by jfcherng** [comment]
Not sure partially working is better than nothing working?

**Comment by rchl** [comment]
But then we'd have to special-case Mac ARM as to not regress the existing platforms.
