### ISSUE TITLE
Bug in abstract_plugin.py broke all of my LSP plugins

### ISSUE THREAD

**Issue by kylebebak** [sublimelsp/lsp_utils#69]
**Feel free to close this**; I know this has been fixed by this release: https://github.com/sublimelsp/lsp_utils/releases/tag/1.13.3

I never installed this module explicitly; it seems like it must be a dep of the `LSP` package. A small bug in the `abstract_plugin.py` file just broke `LSP-bash`, `LSP-json`, `LSP-pyright` and `LSP-typescript` for me.

If this is required by the `LSP` package, might it be better to pull it into that package? If small changes in this package can break all of Sublime LSP, it seems like it would be safer to have the code in there.

Sublime LSP [is heavily tested](https://github.com/sublimelsp/LSP/tree/main/tests), while this repo is not

**Comment by rchl** [comment]
This package is not used directly or required by the LSP package. It's a dependency of (some of) the LSP-* helper packages.

I think the solution to this is not to merge it with LSP but just add proper testing.
