### ISSUE TITLE
Is Node v12 too old?

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/lsp_utils#78]
`lsp_utils` installs Node v12 while some packages requires Node v14 like servers which comes from VSCode: `LSP-css`, `LSP-html` (not sure about the latest master json server in VSCode's repo).

The major problem using Node v14 is that if you are on Windows 7, you have to set env variable `NODE_SKIP_PLATFORM_CHECK` to `1` as it's not official supported. ([details](https://github.com/nodejs/node/issues/33000#issuecomment-644530517))

References
---

- Node.js release schedule: https://github.com/nodejs/Release#release-schedule
- Previous PR: https://github.com/sublimelsp/lsp_utils/pull/59

**Comment by rchl** [comment]
The only thing that makes it difficult is if would want to clear the old node instance somehow. But maybe we don't have to, not sure.

**Comment by jfcherng** [comment]
It could be removed in a later, another PR anyway. Or, we stuck at v12 forever.
