### ISSUE TITLE
Don't show error in status bar when ST node is used

### ISSUE THREAD

**Issue by rwols** [sublimelsp/lsp_utils#80]
In the ST console I see these two messages:

```
LSP-pyright: Error: Ignoring system Node.js runtime due to an error. Node.js version requirement failed. Expected minimum: 14.0.0, got 12.13.1.
LSP: Resolved Node Runtime for client LSP-pyright: NodeRuntimeLocal(node: /home/raoul/.cache/sublime-text-3/Package Storage/lsp_utils/node-runtime/14.17.6/node/bin/node, npm: /home/raoul/.cache/sublime-text-3/Package Storage/lsp_utils/node-runtime/14.17.6/node/lib/node_modules/npm/bin/npm-cli.js, version: 14.17.6)
```

This is OK but it also shows up in the status bar when the server is spawned:

![image](https://user-images.githubusercontent.com/2431823/135715599-879e65ed-efe3-48f2-80c0-3525302e0692.png)

I think this is a bit confusing for end-users cause there's really no error.

**Comment by rchl** [comment]
The question is whether it's still useful to know when the `local` (from `lsp_utils`) node is used because the `system` one was missing or not matching the expected version.

And if so, whether it should be a `print` or `debug_log`...

**Comment by rchl** [comment]
No errors will be reported anymore in https://github.com/sublimelsp/lsp_utils/releases/tag/v2.1.0
