### ISSUE TITLE
[Feature Request] Restrict max supported Node.js version

### ISSUE THREAD

**Issue by jfcherng** [sublimelsp/lsp_utils#89]
This feature request comes from https://github.com/TheSecEng/LSP-copilot/issues/51. The Copilot server files are compiled in WASM files, which freezes ST if the user uses Node v18. Having `minimum_node_version()` is not enough.

I am imaging something like the following:

```py
class NpmClientHandler(GenericClientHandler):
    @classmethod
    def maximum_node_version(cls) -> Optional[Tuple[int, int, int]]:
        return None
```

Or even better, deprecates `minimum_node_version()` and introduces

```py
class NpmClientHandler(GenericClientHandler):
    @classmethod
    def support_node_version(cls, node_version: Tuple[int, int, int]) -> bool:
        """Whether the given Node version is supported by this client."""
        return True

    @classmethod
    def unsupport_node_message(cls, node_version: Tuple[int, int, int]) -> str:
        return "Node.js {} is not supported. Supported versions are v16 and v17.".format('.'.join(node_version))
```

Or 

```py
class NpmClientHandler(GenericClientHandler):
    @classmethod
    def support_node_version(cls, node_version: Tuple[int, int, int]) -> Union[Literal[True], str]:
        """Whether the given Node version is supported by this client."""
        return True  # or error message
```

**Comment by rchl** [comment]
I'm thinking... deprecate current class method and introduce one that returns semantic version (can be a range).

```py
    @classmethod
    def supported_node_version(cls) -> str:
        return '16 - 18'
```

Then we'd need to also vendor https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification or https://github.com/FichteFoll/pysemver to handle semantic version matching.

**Comment by jfcherng** [comment]
Whatever works ;)
